"""Ajouter exchange_with_user_id à ChangeRequest

Revision ID: 683aa24e85e1
Revises: 7b3517dd7b36
Create Date: 2025-04-11 14:57:48.299584

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '683aa24e85e1'
down_revision = '7b3517dd7b36'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_with_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_change_requests_exchange_with_user_id',  # Nom de la contrainte
            'users',                                    # Table cible
            ['exchange_with_user_id'],                  # Colonne source
            ['id']                                      # Colonne cible
        )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_change_requests_exchange_with_user_id', type_='foreignkey')
        batch_op.drop_column('exchange_with_user_id')

    # ### end Alembic commands ###