"""Add current_data_entry_id and team_lead_id to ChangeRequest

Revision ID: a389f1db2ed7
Revises: 
Create Date: 2025-04-03 21:57:54.707266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a389f1db2ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_data_entry_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_lead_id', sa.Integer(), nullable=True))
        batch_op.alter_column('new_district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(
            'fk_change_requests_current_data_entry_id_users',
            'users',
            ['current_data_entry_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_change_requests_team_lead_id_users',
            'users',
            ['team_lead_id'],
            ['id']
        )

    with op.batch_alter_table('team_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_reports', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_change_requests_current_data_entry_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_change_requests_team_lead_id_users', type_='foreignkey')
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('new_district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('team_lead_id')
        batch_op.drop_column('current_data_entry_id')

    # Restaurer la table team_memberships si nécessaire
    op.create_table('team_memberships',
        sa.Column('team_lead_id', sa.INTEGER(), nullable=False),
        sa.Column('member_id', sa.INTEGER(), nullable=True),
        sa.Column('location_id', sa.INTEGER(), nullable=False),
        sa.Column('date_joined', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
        sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('team_lead_id', 'location_id')
    )
    # ### end Alembic commands ###