name: Déploiement Flask

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Prepare environment
        env:
          DATABASE_URI: sqlite:///${{ github.workspace }}/instance/production.db
        run: |
          mkdir -p instance
          touch instance/production.db
          chmod 644 instance/production.db
          echo "SQLALCHEMY_DATABASE_URI=$DATABASE_URI" >> .env
      
      - name: Run migrations
        env:
          FLASK_APP: run.py
          FLASK_ENV: production
        run: |
          flask db upgrade
      
      - name: Run tests
        run: |
          pytest tests/ -v
      
      - name: Run application
        env:
          FLASK_APP: run.py
          FLASK_ENV: production
        run: |
          gunicorn --bind 0.0.0.0:$PORT run:app