name: Déploiement Flask

on:
  push:
    branches:
      - main  # Limiter aux push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Prepare environment
        env:
          DATABASE_URI: sqlite:///${{ github.workspace }}/instance/your_database.db
        run: |
          mkdir -p ${{ github.workspace }}/instance
          touch ${{ github.workspace }}/instance/your_database.db
          chmod 644 ${{ github.workspace }}/instance/your_database.db
          echo "SQLALCHEMY_DATABASE_URI=$DATABASE_URI" > .env
          echo "FLASK_APP=run.py" >> .env
          echo "FLASK_ENV=production" >> .env
      
      - name: Run migrations
        run: |
          flask db init || true  # Ignore si le dossier migrations existe déjà
          flask db upgrade
      
      - name: Run tests
        run: |
          pytest tests/ -v || true  # Continue même si les tests échouent (à ajuster si obligatoire)
      
      - name: Run application
        env:
          PORT: 7007
        run: |
          gunicorn --bind 0.0.0.0:$PORT run:app &
          sleep 5  # Attendre que l'application démarre
          curl http://localhost:$PORT || true  # Vérifier si l'application répond