name: Déploiement Flask

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up environment
        run: |
          mkdir -p /tmp
          touch /tmp/test.db
          chmod 777 /tmp
          chmod 666 /tmp/test.db
      
      - name: Run migrations
        env:
          FLASK_APP: run.py
        run: |
          flask db upgrade
      
      - name: Run application
        env:
          FLASK_APP: run.py
          GITHUB_ACTIONS: 'true'  # Important pour activer la config CI
        run: |
          python run.py